services:
  yolo_service1:
    build: ./WildDetectorA     # Use the Dockerfile in the specified directory
    container_name: wild_yoloA
    environment:
      - RUNNING_PORT=5000
    privileged: true
    volumes:
      - ./models/:/usr/src/ultralytics/models/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
    runtime: nvidia       # Enables GPU-accelerated workloads, without this runtime the container cannot utilize GPU hardware
    network_mode: host    # Useful for performance-critical applications like those requiring low-latency networking or GPU access

  yolo_service2:
    build: ./WildDetectorA     # Use the Dockerfile in the specified directory
    container_name: wild_yoloA
    environment:
      - RUNNING_PORT=5010
    privileged: true
    volumes:
      - ./models/:/usr/src/ultralytics/models/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
    runtime: nvidia       # Enables GPU-accelerated workloads, without this runtime the container cannot utilize GPU hardware
    network_mode: host    # Useful for performance-critical applications like those requiring low-latency networking or GPU access
